### ISSUE TITLE
Build failure with GHC 8

### ISSUE THREAD

**Issue by snoyberg** [tomjaguarpaw/product-profunctors#16]
> /tmp/stackage-build8$ stack unpack product-profunctors-0.7.0.2
Unpacked product-profunctors-0.7.0.2 to /tmp/stackage-build8/product-profunctors-0.7.0.2/
> /tmp/stackage-build8/product-profunctors-0.7.0.2$ runghc -clear-package-db -global-package-db -package-db=/home/stackage/work/builds/nightly/pkgdb Setup configure --package-db=clear --package-db=global --package-db=/home/stackage/work/builds/nightly/pkgdb --libdir=/home/stackage/work/builds/nightly/lib --bindir=/home/stackage/work/builds/nightly/bin --datadir=/home/stackage/work/builds/nightly/share --libexecdir=/home/stackage/work/builds/nightly/libexec --sysconfdir=/home/stackage/work/builds/nightly/etc --docdir=/home/stackage/work/builds/nightly/doc/product-profunctors-0.7.0.2 --htmldir=/home/stackage/work/builds/nightly/doc/product-profunctors-0.7.0.2 --haddockdir=/home/stackage/work/builds/nightly/doc/product-profunctors-0.7.0.2 --flags=
Configuring product-profunctors-0.7.0.2...
> /tmp/stackage-build8/product-profunctors-0.7.0.2$ runghc -clear-package-db -global-package-db -package-db=/home/stackage/work/builds/nightly/pkgdb Setup build
Building product-profunctors-0.7.0.2...
Preprocessing library product-profunctors-0.7.0.2...
[1 of 7] Compiling Data.Profunctor.Product.Tuples ( Data/Profunctor/Product/Tuples.hs, dist/build/Data/Profunctor/Product/Tuples.o )
[2 of 7] Compiling Data.Profunctor.Product.Flatten ( Data/Profunctor/Product/Flatten.hs, dist/build/Data/Profunctor/Product/Flatten.o )
[3 of 7] Compiling Data.Profunctor.Product.Newtype ( Data/Profunctor/Product/Newtype.hs, dist/build/Data/Profunctor/Product/Newtype.o )
[4 of 7] Compiling Data.Profunctor.Product ( Data/Profunctor/Product.hs, dist/build/Data/Profunctor/Product.o )

Data/Profunctor/Product.hs:156:1: warning: [-Wredundant-constraints]
    • Redundant constraint: ProductProfunctor p
    • In the type signature for:
           pT1 :: ProductProfunctor p => T1 (p a1 b1) -> p (T1 a1) (T1 b1)
[5 of 7] Compiling Data.Profunctor.Product.Default ( Data/Profunctor/Product/Default.hs, dist/build/Data/Profunctor/Product/Default.o )
[6 of 7] Compiling Data.Profunctor.Product.Internal.TH ( Data/Profunctor/Product/Internal/TH.hs, dist/build/Data/Profunctor/Product/Internal/TH.o )

Data/Profunctor/Product/Internal/TH.hs:62:3: error:
    • Couldn't match type ‘[Dec] -> Dec’ with ‘Dec’
      Expected type: Q [Dec]
        Actual type: Q [[Dec] -> Dec]
    • In a stmt of a 'do' block:
        return [InstanceD [] (ConT ''N.Newtype `AppT` ConT tyName) body]
      In the expression:
        do { x <- newName "x";
             let body = ...;
             return [InstanceD [] (ConT ''N.Newtype `AppT` ConT tyName) body] }
      In an equation for ‘newtypeInstance’:
          newtypeInstance conName tyName
            = do { x <- newName "x";
                   let body = ...;
                   return [InstanceD ... (ConT ... `AppT` ConT tyName) body] }

Data/Profunctor/Product/Internal/TH.hs:62:21: error:
    • Couldn't match expected type ‘Maybe
                                      Language.Haskell.TH.Syntax.Overlap’
                  with actual type ‘[t0]’
    • In the first argument of ‘InstanceD’, namely ‘[]’
      In the expression:
        InstanceD [] (ConT ''N.Newtype `AppT` ConT tyName) body
      In the first argument of ‘return’, namely
        ‘[InstanceD [] (ConT ''N.Newtype `AppT` ConT tyName) body]’

Data/Profunctor/Product/Internal/TH.hs:62:25: error:
    • Couldn't match type ‘Type’
                     with ‘[Language.Haskell.TH.Syntax.Pred]’
      Expected type: Language.Haskell.TH.Syntax.Cxt
        Actual type: Type
    • In the second argument of ‘InstanceD’, namely
        ‘(ConT ''N.Newtype `AppT` ConT tyName)’
      In the expression:
        InstanceD [] (ConT ''N.Newtype `AppT` ConT tyName) body
      In the first argument of ‘return’, namely
        ‘[InstanceD [] (ConT ''N.Newtype `AppT` ConT tyName) body]’

Data/Profunctor/Product/Internal/TH.hs:62:62: error:
    • Couldn't match expected type ‘Type’ with actual type ‘[Dec]’
    • In the third argument of ‘InstanceD’, namely ‘body’
      In the expression:
        InstanceD [] (ConT ''N.Newtype `AppT` ConT tyName) body
      In the first argument of ‘return’, namely
        ‘[InstanceD [] (ConT ''N.Newtype `AppT` ConT tyName) body]’

Data/Profunctor/Product/Internal/TH.hs:65:29: error:
    • The constructor ‘DataD’ should have 6 arguments, but has been given 5
    • In the pattern: DataD _cxt tyName tyVars constructors _deriving
      In the pattern:
        TyConI (DataD _cxt tyName tyVars constructors _deriving)
      In an equation for ‘dataDecStuffOfInfo’:
          dataDecStuffOfInfo
            (TyConI (DataD _cxt tyName tyVars constructors _deriving))
            = do { (conName, conTys) <- extractConstructorStuff constructors;
                   let tyVars' = ...;
                   return (tyName, tyVars', conName, conTys) }

Data/Profunctor/Product/Internal/TH.hs:105:70: error:
    • Couldn't match type ‘[Dec] -> Dec’ with ‘Dec’
      Expected type: Q Dec
        Actual type: Q ([Dec] -> Dec)
    • In the expression: instanceDec
      In an equation for ‘instanceDefinition’:
          instanceDefinition
            tyName'
            numTyVars
            numConVars
            adaptorName'
            conName
            = instanceDec
            where
                instanceDec
                  = fmap (\ i -> InstanceD i instanceType [...]) instanceCxt
                instanceCxt = mapM (uncurry classP) (pClass : defClasses)
                pClass :: Monad m => (Name, [m Type])
                pClass = (''ProductProfunctor, [return (varTS "p")])
                ....

Data/Profunctor/Product/Internal/TH.hs:106:47: error:
    • Couldn't match type ‘Type’
                     with ‘[Language.Haskell.TH.Syntax.Pred]’
      Expected type: Language.Haskell.TH.Syntax.Cxt
        Actual type: Type
    • In the second argument of ‘InstanceD’, namely ‘instanceType’
      In the expression: InstanceD i instanceType [defDefinition]
      In the first argument of ‘fmap’, namely
        ‘(\ i -> InstanceD i instanceType [defDefinition])’

Data/Profunctor/Product/Internal/TH.hs:106:60: error:
    • Couldn't match expected type ‘Type’ with actual type ‘[Dec]’
    • In the third argument of ‘InstanceD’, namely ‘[defDefinition]’
      In the expression: InstanceD i instanceType [defDefinition]
      In the first argument of ‘fmap’, namely
        ‘(\ i -> InstanceD i instanceType [defDefinition])’

Data/Profunctor/Product/Internal/TH.hs:107:23: error:
    • Couldn't match type ‘[Language.Haskell.TH.Syntax.Pred]’
                     with ‘Maybe Language.Haskell.TH.Syntax.Overlap’
      Expected type: Q (Maybe Language.Haskell.TH.Syntax.Overlap)
        Actual type: Q [Language.Haskell.TH.Syntax.Pred]
    • In the second argument of ‘fmap’, namely ‘instanceCxt’
      In the expression:
        fmap (\ i -> InstanceD i instanceType [defDefinition]) instanceCxt
      In an equation for ‘instanceDec’:
          instanceDec
            = fmap
                (\ i -> InstanceD i instanceType [defDefinition]) instanceCxt

**Comment by tomjaguarpaw** [comment]
Thanks. https://hackage.haskell.org/package/product-profunctors-0.7.1.0 should fix this.

**Comment by tomjaguarpaw** [comment]
Assuming this is fixed.
