### ISSUE TITLE
Why is (***!) being considered for removal?

### ISSUE THREAD

**Issue by endgame** [tomjaguarpaw/product-profunctors#37]
This refers to the comments on the [haddock for `(***!)`](http://hackage.haskell.org/package/product-profunctors-0.8.0.3/docs/Data-Profunctor-Product.html#v:-42--42--42--33-):

> You probably never want to use `***!` and it may be deprecated in a future version.

I find it useful when building aggregators in opaleye, often writing things like `aggregate (groupBy ***! max) $ proc () -> do ...`. Is there a better or more-recommended way to do that?

**Comment by sjoerdvisscher** [comment]
Yes, you can use the `Applicative` operators: `aggregate ((,) <$> groupBy <*> max) $ proc () -> do ...`

**Comment by tomjaguarpaw** [comment]
Hello @endgame.  You can either do what @sjoerdvisscher suggested or use

    p2 (groupBy, max)

Can I ask how you even found out about `***!`?  If it's in some documentation that I wrote then I should probably change it!

**Comment by endgame** [comment]
> Can I ask how you even found out about `***!`?

I think the stackage snapshot I was using pulled in the [old version of product-profunctors](https://hackage.haskell.org/package/product-profunctors-0.7.1.0/docs/Data-Profunctor-Product.html) and I picked it up from reading the class definition.

Now that I have a replacement, I have no objection to its removal.
